a) Write a code taking as input a matrix A of size m× n and a vector b
of size m×1, where m and n are arbitrarily large numbers and m < n,
constructing the augmented matrix and performing
ˆ REF, and
ˆ RREF
without using any built-in functions. In case you encounter any division
by 0, you can choose a different A and/or b.

b)Identify the pivot and non-pivot columns and find the particular solution
and solutions to Ax = 0.

In [85]:
import numpy as np

def print_matrix(matrix):
    for row in matrix:
        print(row)
            
def swap_rows(matrix, row1, row2):
    """Swaps two rows of a matrix."""
    for i in range(len(matrix[0])):
        matrix[row1][i], matrix[row2][i] = matrix[row2][i],matrix[row1][i]

def multiply_row(matrix, row, factor):
    """Multiplies a row of a matrix by a factor."""
    for i in range(len(matrix[0])):
        matrix[row][i] *= factor

def add_rows(matrix, row1, row2, factor):
    """Adds a multiple of one row to another row."""
    for i in range(len(matrix[0])):
        matrix[row2][i] += factor * matrix[row1][i]

def row_echelon_form(matrix):
    """Calculates the Row Echelon Form (REF) of a matrix."""
    m, n = len(matrix), len(matrix[0])

    for i in range(m):
        # Find pivot element
        pivot_row = i
        for j in range(i + 1, m):
            if abs(matrix[j][i]) > abs(matrix[pivot_row][i]):
                pivot_row = j

        # Swap rows if necessary
        if pivot_row != i:
            swap_rows(matrix, i, pivot_row)

        # Eliminate elements below the pivot
        for j in range(i + 1, m):
            factor = matrix[j][i] / matrix[i][i]
            add_rows(matrix, i, j, -factor)

    return matrix

def reduced_row_echelon_form(matrix):
    """Calculates the Reduced Row Echelon Form (RREF) of a matrix."""
    matrix = ref(matrix)
    m, n = len(matrix), len(matrix[0])

    for i in range(m - 1, -1, -1):
        # Normalize pivot element
        if abs(matrix[i][i]) > 1e-10:
            multiply_row(matrix, i, 1 / matrix[i][i])

        # Eliminate elements above the pivot
        for j in range(i - 1, -1, -1):
            factor = matrix[j][i]
            add_rows(matrix, i, j, -factor)
    return matrix

# Construct augmented matrix
#input sample1
A = np.array([[5,2,-1,0,1,-1,1], [3,-4, 1, -2, -1,1,0], [1, 2, 3, -1, 1, 1, 1], [1,3,-1,-3,3,3,-1], [10, 1,-1,4,0,-3,3]], dtype=np.float64)
b = np.array([2,5,-5,7,6], dtype=np.float64)

augmented_matrix = np.hstack((A, b.reshape(-1, 1)))
print("Original Augmented Matrix:\n",augmented_matrix)

# Perform REF
matrix = np.copy(augmented_matrix)

ref_matrix = ref(matrix)
print("\nRow Echelon Form (REF):\n",ref_matrix)

# Perform RREF
rref_matrix = rref(matrix)
np.set_printoptions(suppress=True)
print("\nReduced Row Echelon Form (RREF):\n",rref_matrix)



Original Augmented Matrix:
 [[ 5.  2. -1.  0.  1. -1.  1.  2.]
 [ 3. -4.  1. -2. -1.  1.  0.  5.]
 [ 1.  2.  3. -1.  1.  1.  1. -5.]
 [ 1.  3. -1. -3.  3.  3. -1.  7.]
 [10.  1. -1.  4.  0. -3.  3.  6.]]

Row Echelon Form (REF):
 [[10.          1.         -1.          4.          0.         -3.
   3.          6.        ]
 [ 0.         -4.3         1.3        -3.2        -1.          1.9
  -0.9         3.2       ]
 [ 0.          0.          3.6744186  -2.81395349  0.55813953  2.13953488
   0.30232558 -4.18604651]
 [ 0.          0.          0.         -5.57594937  2.32911392  4.59493671
  -1.90506329  8.53164557]
 [ 0.          0.          0.          0.         -0.65834279 -1.40749149
   0.26674234 -4.75936436]]

Reduced Row Echelon Form (RREF):
 [[ 1.          0.         -0.          0.          0.         -0.20689655
   0.23275862  0.28103448]
 [-0.          1.         -0.         -0.         -0.         -0.89655172
   0.25862069 -3.86551724]
 [ 0.          0.          1.          0. 

b)Identify the pivot and non-pivot columns and find the particular solution
and solutions to Ax = 0.
Deliverables: The code snippet showing the pivot and non-pivot
columns, particular solution and the solutions to Ax = 0

In [79]:
import numpy as np

def find_nonzero_row(matrix, pivot_row, col):
    nrows = matrix.shape[0]
    for row in range(pivot_row, nrows):
        if matrix[row, col] != 0:
            return row
    return None
 
def swap_rows(matrix, row1, row2):
    matrix[[row1, row2]] = matrix[[row2, row1]]
 
def make_pivot_one(matrix, pivot_row, col):
    pivot_element = matrix[pivot_row, col]
    matrix[pivot_row] /= pivot_element
 
def eliminate_below(matrix, pivot_row, col):
    nrows = matrix.shape[0]
    for row in range(pivot_row + 1, nrows):
        if (matrix[row][col] != 0):
            factor = matrix[row, col]
            matrix[row] -= factor * matrix[pivot_row]

def eliminate_above(matrix, pivot_row, col):
    for row in range(0, pivot_row):
        if (matrix[row][col] != 0):
            factor = matrix[row, col]
            matrix[row] -= factor * matrix[pivot_row]
 
def row_echelon_form(matrix):
    ncols = matrix.shape[1]
    pivot_row = 0
    
    for col in range(ncols):
        nonzero_row = find_nonzero_row(matrix, pivot_row, col)
        if nonzero_row is not None:
            if (pivot_row != nonzero_row):
                swap_rows(matrix, pivot_row, nonzero_row)
            make_pivot_one(matrix, pivot_row, col)
            eliminate_below(matrix, pivot_row, col)
            pivot_row += 1
    return matrix

def reduced_row_echelon_form(refMatrix):
    nrows = refMatrix.shape[0]
    ncols = refMatrix.shape[1]
    pivot_row = 1
    for col in range(pivot_row,ncols):
        if (refMatrix[pivot_row][col] == 1):
            eliminate_above(refMatrix, pivot_row, col)
        else:
            continue
        pivot_row += 1
        if(pivot_row >= nrows):
            break
    return refMatrix

In [84]:

import numpy as np
  

def minus_one_padding(rrefMatrix):
    nRows = rrefMatrix.shape[0]
    nCols = rrefMatrix.shape[1]
    
    # Find pivot and non pivot columns
    pivots = pivot_columns(rrefMatrix)
    nonPivots = np.array(list(set(np.arange(rrefMatrix.shape[1] -1)) - set(pivots)))

    for i in nonPivots:
        rowToInsert = np.zeros(nCols)
        rowToInsert[i] = -1
        rrefMatrix = np.insert(rrefMatrix, i, rowToInsert, axis=0)
    
    res = rrefMatrix[~np.all(rrefMatrix == 0, axis=1)]
    return res   

def pivot_columns(mat):
    pivot_columns = []
    non_pivot_columns = []
    rows, cols = len(mat), len(mat[0])

    for j in range(cols):
        col = [mat[i][j] for i in range(rows)]
        if col.count(0) == rows - 1 and col.count(1) == 1:
            pivot_columns.append(j)
        else:
            non_pivot_columns.append(j)
    return np.array(pivot_columns)
  
def is_row_echelon_form(matrix):
    if not matrix.any():
        return False
 
    rows = matrix.shape[0]
    cols = matrix.shape[1]
    prev_leading_col = -1
 
    for row in range(rows):
        leading_col_found = False
        for col in range(cols):
            if matrix[row, col] != 0:
                if col <= prev_leading_col:
                    return False
                prev_leading_col = col
                leading_col_found = True
                break
        if not leading_col_found and any(matrix[row, col] != 0 for col in range(cols)):
            return False
    return True

def Solve_Linear_System(A,b):
    # Augmented Matrix A|B
    AB_augmented = np.hstack((A, b.reshape(-1, 1)))

    nRows = A.shape[0]
    nCols = A.shape[1]

    # 2. REF   
    refA = row_echelon_form(A)
    refAugmentedAb = row_echelon_form(AB_augmented)

    if not is_row_echelon_form(refA) or not is_row_echelon_form(refAugmentedAb):
        print("Not in REF!")
        return None
        
    pivotsA = pivot_columns(refA)
    pivotsAB = pivot_columns(refAugmentedAb)

    if (pivotsA.size < pivotsAB.size):
        print("No solution. The system is inconsistent.")
        return None
    
    print("RREF matrix for A|B")
    rref = reduced_row_echelon_form(refAugmentedAb)
    print(rref)
    
    pivots_rref = pivot_columns(rref)
    non_pivots_rref = np.array(list(set(np.arange(rref.shape[1] -1)) - set(pivots_rref)))
    print("pivot columns of rref:\n",pivot_columns(rref))
    print("non pivot columns of rref:\n",non_pivots_rref)
    
    
    if (nRows < nCols or pivotsA.size < nCols):
        print("The system has many solutions")    
        minusOnePaddedMatrix = minus_one_padding(refAugmentedAb)
        particularSolution = minusOnePaddedMatrix[:,nCols]
        nonPivots = np.array(list(set(np.arange(refAugmentedAb.shape[1] -1)) - set(pivotsA)))

        generalSolutions = np.zeros((nonPivots.size, nCols))
        for i in range(nonPivots.size):
            generalSolutions[i] = minusOnePaddedMatrix[0:,nonPivots[i]]
        print("The particular solution")
        print(particularSolution)
        print("The general solutions to AX = 0")
        print(generalSolutions)
    
    if (pivotsA.size == nCols):
        print("The system has unique solution. The last column in RREF A|B is the solution")
        print(rref[:,nCols])

# 1. INPUT


import numpy as np
  

def minus_one_padding(rrefMatrix):
    nRows = rrefMatrix.shape[0]
    nCols = rrefMatrix.shape[1]
    
    # Find pivot and non pivot columns
    pivots = pivot_columns(rrefMatrix)
    nonPivots = np.array(list(set(np.arange(rrefMatrix.shape[1] -1)) - set(pivots)))

    for i in nonPivots:
        rowToInsert = np.zeros(nCols)
        rowToInsert[i] = -1
        rrefMatrix = np.insert(rrefMatrix, i, rowToInsert, axis=0)
    
    res = rrefMatrix[~np.all(rrefMatrix == 0, axis=1)]
    return res   

def pivot_columns(mat):
    pivot_columns = []
    non_pivot_columns = []
    rows, cols = len(mat), len(mat[0])

    for j in range(cols):
        col = [mat[i][j] for i in range(rows)]
        if col.count(0) == rows - 1 and col.count(1) == 1:
            pivot_columns.append(j)
        else:
            non_pivot_columns.append(j)
    return np.array(pivot_columns)
  
def is_row_echelon_form(matrix):
    if not matrix.any():
        return False
 
    rows = matrix.shape[0]
    cols = matrix.shape[1]
    prev_leading_col = -1
 
    for row in range(rows):
        leading_col_found = False
        for col in range(cols):
            if matrix[row, col] != 0:
                if col <= prev_leading_col:
                    return False
                prev_leading_col = col
                leading_col_found = True
                break
        if not leading_col_found and any(matrix[row, col] != 0 for col in range(cols)):
            return False
    return True

def Solve_Linear_System(A,b):
    # Augmented Matrix A|B
    AB_augmented = np.hstack((A, b.reshape(-1, 1)))

    nRows = A.shape[0]
    nCols = A.shape[1]

    # 2. REF   
    refA = row_echelon_form(A)
    refAugmentedAb = row_echelon_form(AB_augmented)

    if not is_row_echelon_form(refA) or not is_row_echelon_form(refAugmentedAb):
        print("Not in REF!")
        return None
        
    pivotsA = pivot_columns(refA)
    pivotsAB = pivot_columns(refAugmentedAb)

    if (pivotsA.size < pivotsAB.size):
        print("No solution. The system is inconsistent.")
        return None
    
    print("RREF matrix for A|B")
    rref = reduced_row_echelon_form(refAugmentedAb)
    print(rref)
    
    pivots_rref = pivot_columns(rref)
    non_pivots_rref = np.array(list(set(np.arange(rref.shape[1] -1)) - set(pivots_rref)))
    print("pivot columns of rref:\n",pivot_columns(rref))
    print("non pivot columns of rref:\n",non_pivots_rref)
    
    
    if (nRows < nCols or pivotsA.size < nCols):
        print("The system has many solutions")    
        minusOnePaddedMatrix = minus_one_padding(refAugmentedAb)
        particularSolution = minusOnePaddedMatrix[:,nCols]
        nonPivots = np.array(list(set(np.arange(refAugmentedAb.shape[1] -1)) - set(pivotsA)))

        generalSolutions = np.zeros((nonPivots.size, nCols))
        for i in range(nonPivots.size):
            generalSolutions[i] = minusOnePaddedMatrix[0:,nonPivots[i]]
        print("The particular solution")
        print(particularSolution)
        print("The general solutions to AX = 0")
        print(generalSolutions)
    
    if (pivotsA.size == nCols):
        print("The system has unique solution. The last column in RREF A|B is the solution")
        print(rref[:,nCols])

# 1. INPUT
#input sample1
#input sample2
A = np.array([[5,2,-1,0,1,-1,1], [3,-4, 1, -2, -1,1,0], [1, 1, 1, -1, 1, 1, 1], [1,1,-1,-3,5,3,-1], [10, 1,-1,4,0,-3,3], [3, 2,-5,3,1,1,-1], [0,1,1,1,1,1,-1]], dtype=np.float64)
b = np.array([[2],[5],[-5],[7],[6]], dtype=np.float64)

Solve_Linear_System(A,b)
#A = np.array([[5,2,-1,0,1,-1,9], [3,-4, 1, -2, -1,3,0], [1, 1, 1, -1, 1, 6, 1], [1,2,-1,-3,5,3,-1], [10, 1,-1,4,0,-3,3]], dtype=np.float64)
#b = np.array([[2],[5],[-5],[7],[6]], dtype=np.float64)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 7 and the array at index 1 has size 5

In [ ]:
Solve_Linear_System(A,b)
A = np.array([[5,2,-1,0,1,-1,9], [3,-4, 1, -2, -1,3,0], [1, 1, 1, -1, 1, 6, 1], [1,2,-1,-3,5,3,-1], [10, 1,-1,4,0,-3,3]], dtype=np.float64)
b = np.array([[2],[5],[-5],[7],[6]], dtype=np.float64)

C)Identify the pivot and non-pivot columns and find the particular solution
and solutions to Ax = 0.
Deliverables: The code snippet showing the pivot and non-pivot
columns, particular solution and the solutions to Ax = 0

In [55]:
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42)

# Generate a random 5x7 matrix A
A = np.random.rand(5, 7)

# Generate a suitable b
b = np.random.rand(5)

print(b)

[0.80839735 0.30461377 0.09767211 0.68423303 0.44015249]


In [ ]:
#input sample1 rref
rref_matrix = np.array([
    [1, -2, 0, 0, -2, 2],
    [0, 0, 1, 0, 1, -1],
    [0, 0, 0, 1, -2, 1],
    [0, 0, 0, 0, 0, 0]
], dtype=int)

In [47]:
#input sample1
A = np.array([
    [2, 3, 6],
    [4, 7, 5],
    [2, 5, 2]
], dtype=np.float64)

b = np.array([[1, 0, 3]], dtype=np.float64)

In [44]:
#input sample2
A = np.array([[5,2,-1,0,1,-1,9], [3,-4, 1, -2, -1,1,0], [1, 1, 1, -1, 1, 6, 1], [1,1,-1,-3,5,3,-1], [10, 1,-1,4,0,-3,3]], dtype=np.float64)
b = np.array([2,5,-5,7,6], dtype=np.float64)

In [52]:
augmented_matrix = augmented_matrix = np.hstack((A, b.reshape(-1, 1)))
print("Original Augmented Matrix:")
print_matrix(augmented_matrix)

Original Augmented Matrix:
[ 5  2 -1  0  1 -1  9  2]
[ 3 -4  1 -2 -1  1  0  5]
[ 1  1  1 -1  1  6  1 -5]
[ 1  1 -1 -3  5  3 -1  7]
[10  1 -1  4  0 -3  3  6]


In [75]:
#input sample2
A = np.array([[5,2,-1,0,1,-1,9], [3,-4, 1, -2, -1,1,0], [1, 1, 1, -1, 1, 6, 1], [1,1,-1,-3,5,3,-1], [10, 1,-1,4,0,-3,3], [3, 2,-5,3,1,1,-1], [0,1,1,1,1,1,-1]], dtype=np.int32)
b = np.array([2,5,-5,7,6], dtype=np.int32)

In [93]:
#input sample2
A = np.array([[5,2,-1,0,1,-1,1], [3,-4, 1, -2, -1,1,0], [1, 1, 1, -1, 1, 1, 1], [1,1,-1,-3,5,3,-1], [10, 1,-1,4,0,-3,3], [3, 2,-5,3,1,1,-1], [0,1,1,1,1,1,-1]], dtype=np.float64)
b = np.array([2,5,-5,7,6], dtype=np.float64)

In [15]:
A = np.array([[-2,4,-2,-1,4], [4,-8,3,-3,1], [1,-2,1,-1,1], [1,-2,0,-3,4]], dtype=np.float64)
b = np.array([-3,2,0,-1], dtype=np.float64)