a)Consider a symmetric and positive definite matrix A of size n × n.
Write a code to construct an elementary matrix for every elementary
row operation that is performed on A and using the theory explained
in the class write the decomposition of A as LU, where L is a lower
triangular matrix and U is an upper triangular matrix.

In [224]:
#LU decomposition input example
A = np.array([[2, -1, 0],
              [-1, 2, -1],
              [0, -1, 2]], dtype=np.float64)

In [11]:

import numpy as np
  
def find_nonzero_row(matrix, pivot_row, col):
    nrows = matrix.shape[0]
    for row in range(pivot_row, nrows):
        if matrix[row, col] != 0:
            return row
    return None
 
def swap_rows(matrix, row1, row2):
    matrix[[row1, row2]] = matrix[[row2, row1]]
 
def make_pivot_one(matrix, pivot_row, col):
    pivot_element = matrix[pivot_row, col]
    matrix[pivot_row] /= pivot_element
 
def eliminate_below(matrix, pivot_row, col):
    nrows = matrix.shape[0]
    for row in range(pivot_row + 1, nrows):
        if (matrix[row][col] != 0):
            factor = matrix[row, col]
            matrix[row] -= factor * matrix[pivot_row]

def eliminate_above(matrix, pivot_row, col):
    for row in range(0, pivot_row):
        if (matrix[row][col] != 0):
            factor = matrix[row, col]
            matrix[row] -= factor * matrix[pivot_row]
 
def row_echelon_form(matrix):
    ncols = matrix.shape[1]
    pivot_row = 0
    
    for col in range(ncols):
        nonzero_row = find_nonzero_row(matrix, pivot_row, col)
        if nonzero_row is not None:
            if (pivot_row != nonzero_row):
                swap_rows(matrix, pivot_row, nonzero_row)
            make_pivot_one(matrix, pivot_row, col)
            eliminate_below(matrix, pivot_row, col)
            pivot_row += 1
    return matrix

def reduced_row_echelon_form(refMatrix):
    nrows = refMatrix.shape[0]
    ncols = refMatrix.shape[1]
    pivot_row = 1
    for col in range(1,ncols):
        if (refMatrix[pivot_row][col] == 1):
            eliminate_above(refMatrix, pivot_row, col)
        else:
            continue
        pivot_row += 1
        if(pivot_row >= nrows):
            break
    return refMatrix

def pivot_columns(rrefMatrix):
    nrows = rrefMatrix.shape[0]
    ncols = rrefMatrix.shape[1]
    pivot_row = 0
    pivot_columns = []
    for col in range(ncols):
        if (rrefMatrix[pivot_row][col] == 1):
            pivot_columns.append(col)
        else:
            continue
        pivot_row += 1
        if(pivot_row >= nrows):
            break
    return pivot_columns
  
def is_row_echelon_form(matrix):
    if not matrix.any():
        return False
 
    rows = matrix.shape[0]
    cols = matrix.shape[1]
    prev_leading_col = -1
 
    for row in range(rows):
        leading_col_found = False
        for col in range(cols):
            if matrix[row, col] != 0:
                if col <= prev_leading_col:
                    return False
                prev_leading_col = col
                leading_col_found = True
                break
        if not leading_col_found and any(matrix[row, col] != 0 for col in range(cols)):
            return False
    return True
 
A = np.array([[5,2,-1,0,1,-1,1], [3,-4, 1, -2, -1,1,0], [1, 2, 3, -1, 1, 1, 1], [1,3,-1,-3,3,3,-1], [10, 1,-1,4,0,-3,3]], dtype=np.float64)
B = np.array([[2],[5],[-5],[7],[6]], dtype=np.float64)

A_augmented = np.hstack((A,B))

# 2. REF   
REF = row_echelon_form(A_augmented)

if is_row_echelon_form(REF):
    print(A_augmented)
    print("In REF")
    print(REF)
    print("Reduced REF")
    rref = reduced_row_echelon_form(REF)
    print(rref)
    pivots = pivot_columns(rref)
    print("pivot columns are")
    print(pivots)
    print("non pivot columns are")
    print(set(np.arange(A_augmented.shape[1])) - set(pivots))

[[ 1.          0.4        -0.2         0.          0.2        -0.2
   0.2         0.4       ]
 [-0.          1.         -0.30769231  0.38461538  0.30769231 -0.30769231
   0.11538462 -0.73076923]
 [ 0.          0.          1.         -0.4375      0.08333333  0.45833333
   0.16666667 -1.14583333]
 [-0.         -0.         -0.          1.         -0.5        -1.
   0.375      -2.125     ]
 [ 0.          0.          0.          0.          1.          2.13793103
  -0.40517241  7.22931034]]
In REF
[[ 1.          0.4        -0.2         0.          0.2        -0.2
   0.2         0.4       ]
 [-0.          1.         -0.30769231  0.38461538  0.30769231 -0.30769231
   0.11538462 -0.73076923]
 [ 0.          0.          1.         -0.4375      0.08333333  0.45833333
   0.16666667 -1.14583333]
 [-0.         -0.         -0.          1.         -0.5        -1.
   0.375      -2.125     ]
 [ 0.          0.          0.          0.          1.          2.13793103
  -0.40517241  7.22931034]]
Reduced REF

In [7]:
import numpy as np

def print_matrix(matrix):
    for row in matrix:
        print(row)
            
def swap_rows(matrix, row1, row2):
    """Swaps two rows of a matrix."""
    for i in range(len(matrix[0])):
        matrix[row1][i], matrix[row2][i] = matrix[row2][i],matrix[row1][i]

def multiply_row(matrix, row, factor):
    """Multiplies a row of a matrix by a factor."""
    for i in range(len(matrix[0])):
        matrix[row][i] *= factor

def add_rows(matrix, row1, row2, factor):
    """Adds a multiple of one row to another row."""
    for i in range(len(matrix[0])):
        matrix[row2][i] += factor * matrix[row1][i]

def row_echelon_form(matrix):
    """Calculates the Row Echelon Form (REF) of a matrix."""
    m, n = len(matrix), len(matrix[0])

    for i in range(m):
        # Find pivot element
        pivot_row = i
        for j in range(i + 1, m):
            if abs(matrix[j][i]) > abs(matrix[pivot_row][i]):
                pivot_row = j

        # Swap rows if necessary
        if pivot_row != i:
            swap_rows(matrix, i, pivot_row)

        # Eliminate elements below the pivot
        for j in range(i + 1, m):
            factor = matrix[j][i] / matrix[i][i]
            add_rows(matrix, i, j, -factor)

    return matrix

def reduced_row_echelon_form(matrix):
    """Calculates the Reduced Row Echelon Form (RREF) of a matrix."""
    matrix = row_echelon_form(matrix)
    m, n = len(matrix), len(matrix[0])

    for i in range(m - 1, -1, -1):
        # Normalize pivot element
        if abs(matrix[i][i]) > 1e-10:
            multiply_row(matrix, i, 1 / matrix[i][i])

        # Eliminate elements above the pivot
        for j in range(i - 1, -1, -1):
            factor = matrix[j][i]
            add_rows(matrix, i, j, -factor)
    return matrix

# Construct augmented matrix
#input sample2
A = np.array([[5,2,-1,0,1,-1,1], [3,-4, 1, -2, -1,1,0], [1, 2, 3, -1, 1, 1, 1], [1,3,-1,-3,3,3,-1], [10, 1,-1,4,0,-3,3]], dtype=np.float64)
b = np.array([2,5,-5,7,6], dtype=np.float64)

augmented_matrix = np.hstack((A, b.reshape(-1, 1)))
print("Original Augmented Matrix:")
print_matrix(augmented_matrix)

# Perform REF
matrix = np.copy(augmented_matrix)

ref_matrix = row_echelon_form(matrix)
print("\nRow Echelon Form (REF):")
print_matrix(ref_matrix)

# Perform RREF
matrix = np.copy(augmented_matrix)
rref_matrix = reduced_row_echelon_form(matrix)
np.set_printoptions(suppress=True)
print("\nReduced Row Echelon Form (RREF):")
print_matrix(rref_matrix)



Original Augmented Matrix:
[ 5.  2. -1.  0.  1. -1.  1.  2.]
[ 3. -4.  1. -2. -1.  1.  0.  5.]
[ 1.  2.  3. -1.  1.  1.  1. -5.]
[ 1.  3. -1. -3.  3.  3. -1.  7.]
[10.  1. -1.  4.  0. -3.  3.  6.]

Row Echelon Form (REF):
[10.  1. -1.  4.  0. -3.  3.  6.]
[ 0.  -4.3  1.3 -3.2 -1.   1.9 -0.9  3.2]
[ 0.          0.          3.6744186  -2.81395349  0.55813953  2.13953488
  0.30232558 -4.18604651]
[ 0.          0.          0.         -5.57594937  2.32911392  4.59493671
 -1.90506329  8.53164557]
[ 0.          0.          0.          0.         -0.65834279 -1.40749149
  0.26674234 -4.75936436]

Reduced Row Echelon Form (RREF):
[ 1.          0.         -0.          0.          0.         -0.20689655
  0.23275862  0.28103448]
[-0.          1.         -0.         -0.         -0.         -0.89655172
  0.25862069 -3.86551724]
[ 0.          0.          1.          0.          0.          0.31034483
  0.27586207 -1.09655172]
[-0.         -0.         -0.          1.         -0.          0.06896552
 

In [153]:
A = np.array([[7, 3, -1, 2], [3, 8, 1, -4], [-1, 1, 4, -1], [2, -4, -1, 6]], dtype=np.float64)

In [192]:
A = np.array([[4,1,2], [1,5,3], [2,3,6]], dtype=np.float64)

In [61]:

A = np.array([[4, -1, 0,9],
              [-1, 5, -1,7],
              [0, -1, 3,3]], dtype=float)

In [118]:
import numpy as np

def lu_decomposition(A):
    n = A.shape[0]
    U = np.copy(A)
    L = np.eye(n)
    for i in range(n - 1):
        for j in range(i + 1, n):
              # Compute the multiplier for the elementary operation
            multiplier = U[j, i] / U[i, i]

               # Update the lower triangular matrix L
            L[j, i] = multiplier

            # Perform the elementary row operation on U
            U[j, i:] -= multiplier * U[i, i:]

    return L, U

# LU decomposition using elementary operations

if (A.shape[0] == A.shape[1]):
    L, U = lu_decomposition(A)
    print("\nLower Triangular Matrix L:")
    print(L)
    print("\nUpper Triangular Matrix U:")
    print(U)
else:
    print("LC decomposition possible only on square matrix, this is not square matrix")
    print(A)


Lower Triangular Matrix L:
[[ 1.          0.          0.          0.        ]
 [ 0.42857143  1.          0.          0.        ]
 [-0.14285714  0.21276596  1.          0.        ]
 [ 0.28571429 -0.72340426  0.08982036  1.        ]]

Upper Triangular Matrix U:
[[ 7.          3.         -1.          2.        ]
 [ 0.          6.71428571  1.42857143 -4.85714286]
 [ 0.          0.          3.55319149  0.31914894]
 [ 0.          0.          0.          1.88622754]]


b) For the above problem, work out the Cholesky’s decomposition

In [230]:
import math
def cholesky_decomposition(A):
    nrows = ncols = A.shape[0]
    L = np.zeros((nrows,ncols), dtype = np.float64)
      
    # Decomposing a matrix into Lower Triangular
    for i in range(nrows):
        for j in range(i+1):
            sum = 0
            if(i == j):
                for k in range(j):
                    sum += pow(L[j][k], 2)
                L[i][j] = math.sqrt(A[i][j] - sum)
            else:  
                for k in range(j):
                    sum += (L[i][k] * L[j][k])
                if(L[j][j] > 0):
                    L[i][j] = (A[i][j] - sum) / L[j][j]
        
    return (L, np.transpose(L),np.matmul(L,np.transpose(L)))

#Find Lower tringle matrix and Transpose of lower triangle matrix
if (A.shape[0] == A.shape[1]):
    L, L_transpose,LLT = cholesky_decomposition(A)
    print("\nLower tringular matrix:\n", L)
    print(" \nTranspose Lower tringular matrix:\n",L_transpose)
    rtol = 1e-5
    atol = 1e-8
    is_matrix_A_LLT_same = np.allclose(A, LLT, rtol=rtol, atol=atol)
    if is_matrix_A_LLT_same:
        print("\nA = LL^T cholesky decomposition is verified\n")
    print( "syemetric positive definite matrix A:\n",A)
    print("\nLower tringular matrix X Transpose Lower tringular matrix L*L^T:\n", LLT)
else:
    print("cholesky decomposition possible only on square matrix, this is not square matrix")
    print(A)


Lower tringular matrix:
 [[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]
 
Transpose Lower tringular matrix:
 [[ 1.41421356 -0.70710678  0.        ]
 [ 0.          1.22474487 -0.81649658]
 [ 0.          0.          1.15470054]]

A = LL^T cholesky decomposition is verified

syemetric positive definite matrix A:
 [[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]

Lower tringular matrix X Transpose Lower tringular matrix L*L^T:
 [[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]


c)c) Given n linearly independent vectors in m dimensions (the corresponding
matrix with these as columns is A of size m × n), with m > n,
read about the QR decomposition of a matrix and generate Q and R.
Deliverables: The code snippet generating Q and R.

In [272]:
import numpy as np

def gram_schmidt(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for k in range(n):
        Q[:, k] = A[:, k]

        for j in range(k):
            R[j, k] = np.dot(Q[:, j].T, A[:, k])
            Q[:, k] -= R[j, k] * Q[:, j]
        # Manual normalization
        norm_q_k = np.sqrt(np.sum(Q[:, k] ** 2))
        R[k, k] = norm_q_k
        Q[:, k] /= norm_q_k

    return Q, R

# Example usage:
A = np.array([[0,-2,1], [1,3,1], [0,0,1],[1,1,5]], dtype=np.float64)

Q, R = gram_schmidt(A)

print("Matrix Q:")
print(Q)
print("\nMatrix R:")
print(R)
print(np.matmul(Q,R))

Matrix Q:
[[ 0.         -0.81649658 -0.5       ]
 [ 0.70710678  0.40824829 -0.5       ]
 [ 0.          0.          0.5       ]
 [ 0.70710678 -0.40824829  0.5       ]]

Matrix R:
[[ 1.41421356  2.82842712  4.24264069]
 [ 0.          2.44948974 -2.44948974]
 [ 0.          0.          2.        ]]
[[ 0. -2.  1.]
 [ 1.  3.  1.]
 [ 0.  0.  1.]
 [ 1.  1.  5.]]


In [283]:
import numpy as np

def gram_schmidt(A):
    m, n = A.shape
    Q = np.zeros((m, n))
    R = np.zeros((n, n))

    for k in range(n):
        Q[:, k] = A[:, k]

        for j in range(k):
            R[j, k] = np.dot(Q[:, j].T, A[:, k])
            Q[:, k] -= R[j, k] * Q[:, j]
        # Manual normalization
        norm_q_k = np.sqrt(np.sum(Q[:, k] ** 2))
        R[k, k] = norm_q_k
        Q[:, k] /= norm_q_k

    return Q, R

# Example usage:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

Q, R = gram_schmidt(A)8
print("original matrix A:")
print(A)
print("\nMatrix Q:")
print(Q)
print("\nMatrix R:")
print(R)
print("Q X R:")
print(np.matmul(Q,R))

original matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix Q:
[[ 0.12309149  0.90453403 -0.90453403]
 [ 0.49236596  0.30151134 -0.30151134]
 [ 0.86164044 -0.30151134  0.30151134]]

Matrix R:
[[ 8.1240384   9.6011363  11.07823419]
 [ 0.          0.90453403  1.80906807]
 [ 0.          0.          0.        ]]
Q X R:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
